services:
  - type: web
    name: app
    env: docker
    dockerfilePath: Dockerfile
    port: 7860
    autoDeploy: true
    envVars:
      - key: CHROMADB_URL
        value: http://chromadb:8000
      - key: OLLAMA_URL
        value: http://ollama:11434

  - type: pservice
    name: chromadb
    env: docker
    image: chromadb/chroma:latest
    port: 8000
    autoDeploy: true
    disk:
      mountPath: /chroma/chroma
      name: chromadb-storage
      sizeGB: 1

  - type: pservice
    name: ollama
    env: docker
    image: ollama/ollama:latest
    port: 11434
    autoDeploy: true
    disk:
      mountPath: /root/.ollama
      name: ollama-storage
      sizeGB: 1
