services:
  - type: web
    name: app
    runtime: docker
    dockerfilePath: Dockerfile
    envVars:
      - key: PORT
        value: "7860"

  - type: web
    name: chromadb
    runtime: docker
    image:
      url: chromadb/chroma:latest
    envVars:
      - key: PORT
        value: "8000"
    disk:
      name: chromadb-data
      mountPath: /chroma/chroma
      sizeGB: 1

  - type: web
    name: ollama
    runtime: docker
    image:
      url: ollama/ollama:latest
    envVars:
      - key: PORT
        value: "11434"
    disk:
      name: ollama-data
      mountPath: /root/.ollama
      sizeGB: 1
